### ISSUE TITLE
RTL Overlay Angular Bug

### ISSUE THREAD

**Issue by emclaug2** [pxblue/storybook-addons#15]
#### Describe the bug
Note that this would not occur if you enter a story with i18n already turned on (i.e., turn on i18n and switch between different stories)This would not happen either if you click the avatar first, and then toggle i18n

#### What is the expected behavior?
RTL Overlay should work regardless of when RTL button is clicked. 

#### What are the steps to reproduce?
1. Go to https://pxblue-angular-library.web.app/?path=/story/components-user-menu--within-a-toolbar  (Or any user menu story)
2. Without touching anything else, toggle the i18n on so that it reads RTL
3. Now click the avatar. Observe what you see in the screenshot

#### Screenshots or links to minimum reproduction example
![image](https://user-images.githubusercontent.com/8997218/105593358-debb6a00-5d60-11eb-9b29-0f1c9600486c.png)

#### Environment

Chrome Windows

**Comment by jeffvg** [comment]
* This is a Story Book issue. Investigate if an add-on fix can fix this

**Comment by jeffvg** [comment]
moved to PXBLUE-1931
