### ISSUE TITLE
User Menu RTL Incorrect

### ISSUE THREAD

**Issue by emclaug2** [pxblue/storybook-addons#27]
#### Describe the bug
Fix the RTL behavior of the user menu.

#### What is the expected behavior?
It should look better. 

#### Screenshots or links to minimum reproduction example
![119987930-8c4ebc00-bf93-11eb-8c8b-6547b2d9a3de](https://user-images.githubusercontent.com/6538289/119989426-2b27e800-bf95-11eb-9033-eef8ee0a0a6b.png)

**Comment by huayunh** [comment]
This is a dup for #26
