### ISSUE TITLE
UI active state does not respect Storybook theme colors

### ISSUE THREAD

**Issue by alycia-docusign** [pxblue/storybook-addons#38]
Screen shot from my Storybook instance:
<img width="187" alt="Screen Shot 2022-03-31 at 4 16 45 PM" src="https://user-images.githubusercontent.com/93614175/161165760-ef945b36-691e-406c-ab74-9eb953a31bcc.png">
<img width="157" alt="Screen Shot 2022-03-31 at 4 26 56 PM" src="https://user-images.githubusercontent.com/93614175/161165765-8bfb0eb1-8152-47d1-b86d-d2ae834862a7.png">

This explicitly set gray underline is problematic because depending on the theme used, this can cause a color contrast issue. For an accessible experience, active states should not be determined by color alone; a visible underline helps to communicate the active state. If theme colors are respected, Storybook users can adjust theme colors to fix color contrast issues.

The line in question: https://github.com/brightlayer-ui/storybook-addons/blob/0b9d46a32b072ad44960a1e2c892846e41df9c96/rtl/src/Tool.tsx#L70

Instead of explicitly setting  a color using `style`, the `IconButton` could instead use the `active` prop like so:
```
active={{ direction === "rtl" }}
```

**Comment by bkarambe** [comment]
We will take a look at this, but we are also open to PRs if you have a fix available.

**Comment by joebochill** [comment]
Hey @alycia-docusign — we've moved away from Storybook as our documentation tool of choice, so going forward, we're no longer going to be maintaining this package. Feel free to make a fork and take it over if it's still valuable for you and your team.
